name: Test Stage

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '11' # Make sure the version is quoted as a string
          distribution: 'adopt' # Specify the distribution (adopt, adopt-openj9, etc.)

      - name: Make Gradlew Executable
        run: chmod +x gradlew # Make the gradlew script executable

      - name: Build with Gradle
        run: ./gradlew build

      - name: Run Tests
        run: ./gradlew test
